# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcc4b9dc23ec224eb0659a325dc6005b6b82c99c0aa8a12d2812361e3c345add132d3df8a5daaa4045799863d026da7565ba3c3b5bf8a021ca8b707ca1bf8032

test:
  secret_key_base: fdd45a0af07eb70ae153f81e2baec912a595611376248e8cc73f5b6cc50bb43db2348f4f57af52d4c07a07aefaeb7c5f61a2700ef8c96f988949c37e1acaeea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
